In [41]:
import numpy as np

### Creating Arrays

In [42]:
# 1D array
arr1 = np.array([1, 2, 3, 4])

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Zeros array
zeros = np.zeros((3, 3))

# Ones array
ones = np.ones((2, 2))

# Identity matrix
identity = np.eye(3)

# Random numbers
random_array = np.random.rand(3, 3)

### Array Properties

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3) - rows, columns
print(arr.size)   # 6 - number of elements
print(arr.dtype)  # int64 - data type of elements
print(arr.ndim)   # 2 - number of dimensions
print(arr.itemsize)  # 8 - size of each element in bytes
print(arr.nbytes)  # 48 - total size of array in bytes

(2, 3)
6
int64
2
8
48


### Indexing and Slicing

In [44]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])      # 20
print(arr[-1])     # 50
print(arr[1:4])    # [20, 30, 40]

# 2D array indexing
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[1, 2])  # 6
print(arr2d[:, 1])  # Select second column

20
50
[20 30 40]
6
[2 5]


### Reshaping Arrays

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = arr.reshape((3, 2)) # [[1, 2], [3, 4], [5, 6]] - 3 rows, 2 columns
flattened = arr.flatten() # [1, 2, 3, 4, 5, 6] - 1D array
print(reshaped)
print()
print(flattened)

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]


### Math Operations

In [46]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # [5, 7, 9] - element-wise addition
print(arr1 * 2)     # [2, 4, 6] - scalar multiplication
print(np.sqrt(arr1))  # Square root
print(np.exp(arr1))  # Exponential
print(np.log(arr1))  # Natural log
print(np.sin(arr1))  # Sine function

[5 7 9]
[2 4 6]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]


### Aggregations

In [47]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))    # 15
print(np.mean(arr))   # 3.0
print(np.max(arr))    # 5
print(np.min(arr))    # 1
print(np.median(arr))  # 3.0
print(np.std(arr))     # Standard deviation
print(np.var(arr))     # Variance

15
3.0
5
1
3.0
1.4142135623730951
2.0


### Stacking and Splitting

In [48]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked = np.vstack((arr1, arr2))  # Vertical stack
hstacked = np.hstack((arr1, arr2))  # Horizontal stack
split = np.hsplit(stacked, 3)  # Split into 3 arrays

### Boolean Masking

In [49]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
filtered = arr[mask]  # [4, 5]

# Conditional replacement
arr[arr < 3] = 0  # Replace values less than 3 with 0


### Linear Algebra

In [50]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = np.dot(A, B)  # Matrix multiplication
inverse = np.linalg.inv(A)  # Inverse of A
transpose = A.T  # Transpose
det = np.linalg.det(A)  # Determinant
eigenvalues, eigenvectors = np.linalg.eig(A)  # Eigenvalues & Eigenvectors

# Set random seed for reproducibility
np.random.seed(42)

### Broadcasting

In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([1, 2, 3])
result = arr + vector  # Adds vector to each row of arr
result

array([[2, 4, 6],
       [5, 7, 9]])

### Sorting

In [52]:
arr = np.array([3, 1, 4, 1, 5, 9, 2])
sorted_arr = np.sort(arr)
indices = np.argsort(arr)  # Returns indices of sorted elements
sorted_arr, indices

(array([1, 1, 2, 3, 4, 5, 9]), array([1, 3, 6, 0, 2, 4, 5]))

### Unique Elements and Counting

In [53]:
arr = np.array([1, 2, 2, 3, 3, 3, 4])
unique_elements = np.unique(arr)
counters = np.bincount(arr)  # Count occurrences of each value

### Save and Load Data

In [54]:
'''
arr = np.array([1, 2, 3, 4, 5])
np.save("array.npy", arr)  # Save to file
loaded_arr = np.load("array.npy")  # Load from file

np.savetxt("array.txt", arr)  # Save as text file
loaded_txt_arr = np.loadtxt("array.txt")  # Load from text file
'''

'\narr = np.array([1, 2, 3, 4, 5])\nnp.save("array.npy", arr)  # Save to file\nloaded_arr = np.load("array.npy")  # Load from file\n\nnp.savetxt("array.txt", arr)  # Save as text file\nloaded_txt_arr = np.loadtxt("array.txt")  # Load from text file\n'